### PR TITLE
Changes needed for performance indicator

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
@pacospace Performance indicator code:

```python
import sys
import os
from pybench.pybench import PyBenchCmdline

_ARGS_ROUNDS = int(os.getenv("ROUNDS", 10))
print("ROUNDS set to %s" % _ARGS_ROUNDS, file=sys.stderr)

# pybench prints stats to stdout, we need to move them to stderr so that amun
# reports back just reported JSON.
original_stdout = sys.stdout
sys.stdout = os.fdopen(os.dup(sys.stderr.fileno()), sys.stdout.mode)
bench = PyBenchCmdline(argv=["pybench", "-n", str(_ARGS_ROUNDS), "-o", "json", "-f", "output.json"])

with open("output.json", "r") as output:
    print(output.read(), file=original_stdout)

sys.exit(bench.exit_code)
```

This way we will still be able to obtain kernel stats about the process as done in PI.

**Comment by pacospace** [comment]
> @pacospace Performance indicator code:
> 
> ```python
> import sys
> import os
> from pybench.pybench import PyBenchCmdline
> 
> _ARGS_ROUNDS = int(os.getenv("ROUNDS", 10))
> print("ROUNDS set to %s" % _ARGS_ROUNDS, file=sys.stderr)
> 
> # pybench prints stats to stdout, we need to move them to stderr so that amun
> # reports back just reported JSON.
> original_stdout = sys.stdout
> sys.stdout = os.fdopen(os.dup(sys.stderr.fileno()), sys.stdout.mode)
> bench = PyBenchCmdline(argv=["pybench", "-n", str(_ARGS_ROUNDS), "-o", "json", "-f", "output.json"])
> 
> with open("output.json", "r") as output:
>     print(output.read(), file=original_stdout)
> 
> sys.exit(bench.exit_code)
> ```
> 
> This way we will still be able to obtain kernel stats about the process as done in PI.

LGTM Thanks :) Do you want to issue new version of `thoth-pybench`: 0.0.5 after this?

**Comment by fridex** [comment]
> > @pacospace Performance indicator code:
> > ```python
> > import sys
> > import os
> > from pybench.pybench import PyBenchCmdline
> > 
> > _ARGS_ROUNDS = int(os.getenv("ROUNDS", 10))
> > print("ROUNDS set to %s" % _ARGS_ROUNDS, file=sys.stderr)
> > 
> > # pybench prints stats to stdout, we need to move them to stderr so that amun
> > # reports back just reported JSON.
> > original_stdout = sys.stdout
> > sys.stdout = os.fdopen(os.dup(sys.stderr.fileno()), sys.stdout.mode)
> > bench = PyBenchCmdline(argv=["pybench", "-n", str(_ARGS_ROUNDS), "-o", "json", "-f", "output.json"])
> > 
> > with open("output.json", "r") as output:
> >     print(output.read(), file=original_stdout)
> > 
> > sys.exit(bench.exit_code)
> > ```
> > 
> > 
> > This way we will still be able to obtain kernel stats about the process as done in PI.
> 
> LGTM Thanks :) Do you want to issue new version of `thoth-pybench`: 0.0.5 after this?

As there were fixes addressed, I think it will be needed.

**Review by pacospace — APPROVED** [review]
Thanks. Let's relase new `thoth-pybench` :1st_place_medal:

**Pull request merged**
